# Generated by Django 6.0.4 on 2026-04-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rango', models.CharField(choices=[('novato', 'Novato'), ('piloto', 'Piloto'), ('comandante', 'Comandante')], default='novato', max_length=20)),
                ('horas_experiencia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('años_experiencia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_tripulación', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('operativa', 'Operativa'), ('en_mantenimiento', 'En Mantenimiento'), ('retirada', 'Retirada')], default='operativa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mision', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('fallida', 'Fallida')], default='planificada', max_length=20)),
                ('astronauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploracion.astronauta')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploracion.nave')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroExploracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planeta_destino', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploracion.mision')),
            ],
        ),
    ]
